apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: celestia-backend
  namespace: PROJECT_ID
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/ingress: all
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containers:
        - image: celestia-backend:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PORT
              value: "8080"
            - name: REQUEST_TIMEOUT
              value: "30"
            - name: MAX_RETRIES
              value: "3"
          envFrom: []
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
      timeoutSeconds: 900
