version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: celestia
      POSTGRES_PASSWORD: celestia
      POSTGRES_DB: celestia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      ENV: development
      PORT: 8080
      DATABASE_URL: postgresql+psycopg2://celestia:celestia@db:5432/celestia
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
volumes:
  pgdata:
