name: Deploy Celestia Backend (Cloud Run - SP)

on:
  workflow_dispatch:

env:
  REGION: southamerica-east1
  SERVICE: celestia-backend
  REPOSITORY: celestia-registry
  QUEUE: celestia-queue
  MIGRATION_JOB: celestia-migrate
  TZ: America/Sao_Paulo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Enable required APIs (idempotent)
        run: |
          gcloud services enable run.googleapis.com artifactregistry.googleapis.com iam.googleapis.com             secretmanager.googleapis.com cloudtasks.googleapis.com cloudscheduler.googleapis.com sqladmin.googleapis.com

      - name: Create Artifact Registry (idempotent)
        run: |
          gcloud artifacts repositories create "$REPOSITORY"             --repository-format=docker --location="$REGION"             --description="Celestia Docker registry" || true

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Prepare pytest.ini & PYTHONPATH
        run: |
          echo '[pytest]' > pytest.ini
          echo 'addopts = -q' >> pytest.ini
          echo 'testpaths = backend/tests' >> pytest.ini
          echo 'pythonpath = backend/src' >> pytest.ini

      - name: Fix requirements (google-cloud-tasks pin) and install
        run: |
          sed -i 's/^google-cloud-tasks==2\.16\.6/google-cloud-tasks==2.19.3/' backend/requirements.txt || true
          python -m pip install -U pip wheel setuptools
          python -m pip install -r backend/requirements.txt
          python -m pip install pytest beautifulsoup4 selectolax lxml httpx selenium

      - name: Run tests (continue on failure)
        run: |
          set +e
          pytest
          echo "pytest exit code: $?"
          set -e

      - name: Docker auth for Artifact Registry
        run: gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev" -q

      - name: Build & Push image
        id: image
        run: |
          TAG="$(date +%Y%m%d-%H%M%S)"
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${TAG}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT
          docker build -t "${IMAGE}" -f backend/Dockerfile .
          docker push "${IMAGE}"

      - name: Expand Cloud Run manifest with image & project
        run: |
          mkdir -p .deploy
          sed "s/PROJECT_ID/${{ secrets.GCP_PROJECT_ID }}/g" infra/cloudrun/cloudrun.yaml > .deploy/cloudrun.expanded.yaml
          sed -i 's|celestia-backend:latest|'"${{ steps.image.outputs.IMAGE }}"'|g' .deploy/cloudrun.expanded.yaml
          cat .deploy/cloudrun.expanded.yaml

      - name: Deploy to Cloud Run (replace)
        run: |
          gcloud run services replace .deploy/cloudrun.expanded.yaml --region="${{ env.REGION }}"

      - name: Allow unauthenticated invoke (temporário)
        run: |
          gcloud run services add-iam-policy-binding "${{ env.SERVICE }}"             --region="${{ env.REGION }}"             --member="allUsers"             --role="roles/run.invoker" || true

      - name: Fetch SERVICE_URL & set as env
        id: svc
        run: |
          URL=$(gcloud run services describe "${{ env.SERVICE }}" --region="${{ env.REGION }}" --format='value(status.url)')
          echo "SERVICE_URL=${URL}" >> $GITHUB_OUTPUT
          gcloud run services update "${{ env.SERVICE }}" --region="${{ env.REGION }}" --set-env-vars "SERVICE_URL=${URL}"

      - name: Ensure Cloud Tasks queue (idempotent)
        run: |
          gcloud tasks queues create "${{ env.QUEUE }}" --location="${{ env.REGION }}" || true

      - name: Upsert Secret Manager secrets (if provided)
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          upsert() {
            local name="$1"; local val="$2"
            [[ -z "$val" ]] && return 0
            gcloud secrets describe "$name" --project "$PROJECT_ID" >/dev/null 2>&1               || echo -n "$val" | gcloud secrets create "$name" --replication-policy=automatic --project "$PROJECT_ID" --data-file=-
            echo -n "$val" | gcloud secrets versions add "$name" --project "$PROJECT_ID" --data-file=- >/dev/null
          }
          upsert database-url "${{ secrets.DATABASE_URL }}"
          upsert telegram-bot-token "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          upsert telegram-chat-id "${{ secrets.TELEGRAM_CHAT_ID }}"
          upsert latam_user "${{ secrets.LATAM_USER }}"
          upsert latam_pass "${{ secrets.LATAM_PASS }}"
          upsert azul_user "${{ secrets.AZUL_USER }}"
          upsert azul_pass "${{ secrets.AZUL_PASS }}"
          upsert smiles_user "${{ secrets.SMILES_USER }}"
          upsert smiles_pass "${{ secrets.SMILES_PASS }}"
          upsert connectmiles_user "${{ secrets.CONNECTMILES_USER }}"
          upsert connectmiles_pass "${{ secrets.CONNECTMILES_PASS }}"
          upsert gol_user "${{ secrets.GOL_USER }}"
          upsert gol_pass "${{ secrets.GOL_PASS }}"
          upsert livelo_user "${{ secrets.LIVELO_USER }}"
          upsert livelo_pass "${{ secrets.LIVELO_PASS }}"

      - name: Create/Update Cloud Run Job for Alembic migrations
        run: |
          gcloud run jobs delete "${{ env.MIGRATION_JOB }}" --region "${{ env.REGION }}" --quiet || true
          gcloud run jobs create "${{ env.MIGRATION_JOB }}"             --image "${{ steps.image.outputs.IMAGE }}"             --region "${{ env.REGION }}"             --set-secrets="DATABASE_URL=database-url:latest"             --command "bash" --args "-lc","alembic upgrade head"

      - name: Execute migrations (Cloud Run Job)
        run: |
          gcloud run jobs execute "${{ env.MIGRATION_JOB }}" --region "${{ env.REGION }}" --wait

      - name: Provision Cloud Scheduler (hourly jobs for 3 routes)
        env:
          SERVICE_URL: ${{ steps.svc.outputs.SERVICE_URL }}
        run: |
          create_job () {
            local NAME="$1"; local BODY="$2"; local SPEC="$3"
            gcloud scheduler jobs create http "$NAME"               --schedule="$SPEC" --time-zone="${{ env.TZ }}"               --http-method=POST --uri="${SERVICE_URL}/search/enqueue"               --oidc-service-account-email="$(gcloud iam service-accounts list --filter='email:celestia-deploy' --format='value(email)' | head -n1)"               --message-body="$BODY"               --location="${{ env.REGION }}" || true
          }
          create_job "hourly-gru-mco" '{"origin":"GRU","destination":"MCO","departure_date":"2025-09-01"}' "3 * * * *"
          create_job "hourly-cgh-sdu" '{"origin":"CGH","destination":"SDU","departure_date":"2025-09-01"}' "13 * * * *"
          create_job "hourly-gru-lis" '{"origin":"GRU","destination":"LIS","departure_date":"2025-09-01"}' "23 * * * *"

      - name: Summary
        run: |
          echo "Service URL: ${{ steps.svc.outputs.SERVICE_URL }}"
          echo "Queue: ${{ env.QUEUE }}"
          echo "Scheduler: hourly-gru-mco, hourly-cgh-sdu, hourly-gru-lis"
