apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: celestia-backend
  namespace: 'PROJECT_ID'
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/launch-stage: GA
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-boost: 'true'
        run.googleapis.com/min-instances: '0'
        run.googleapis.com/max-instances: '20'
        autoscaling.knative.dev/target: '80'
    spec:
      containerConcurrency: 80
      containers:
      - image: southamerica-east1-docker.pkg.dev/PROJECT_ID/celestia-registry/celestia-backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: ENV
          value: production
        - name: PORT
          value: '8080'
        - name: APP_MODULE
          value: 'api.main:app'
        - name: TELEGRAM_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: telegram-webhook-secret
              key: latest
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: latest
        - name: CODEX_API_KEY
          valueFrom:
            secretKeyRef:
              name: codex-api-key
              key: latest
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: latest
        - name: CELESTIA_API_KEY
          valueFrom:
            secretKeyRef:
              name: celestia-api-key
              key: latest
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-token
              key: latest
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-url
              key: latest
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '0.5'
            memory: 512Mi
      timeoutSeconds: 300
      serviceAccountName: celestia-deploy@PROJECT_ID.iam.gserviceaccount.com
