from typing import Protocol, List, Dict, Optional

class Scraper(Protocol):
    async def search(self, origin: str, destination: str, date: str, **kwargs) -> List[Dict]: ...
    async def login(self) -> None: ...

class Parser(Protocol):
    def parse(self, html: str) -> List[Dict]: ...

# Resultado normalizado mínimo
# route: 'GRU-MCO', date: 'YYYY-MM-DD', price: float, currency: 'BRL'|'USD'|'...' 
# source: 'latam'|..., program: 'LATAM'|'Azul'|..., fare_type: 'cash'|'miles', cabin: 'economy'|'business'|...
