name: Deploy Placeholder

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Placeholder de deploy
        run: echo "Em breve: deploy para VPS, Render ou Railway"
