name: Ops - Provision Cloud Scheduler (Hourly Jobs)

on:
  workflow_dispatch:

env:
  REGION: southamerica-east1
  SERVICE: celestia-backend

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Run scheduler setup
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: bash infra/scheduler/setup_hourly.sh
